### ISSUE TITLE
Merge config sections

### ISSUE THREAD

**Issue by loyd** [elfo-rs/elfo#30]
Works fine:
```toml
[common]
system.logging.targets.hyper.max_level = "Info"
[a]
system.logging.targets.reqwest.max_level = "Info"
```

Broken:
```toml
[common.system.logging.targets]
hyper.max_level = "Info"

[a]
system.logging.targets.reqwest.max_level = "Info"
```
